/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BannedRouteImport } from './routes/banned'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAnalysisRouteImport } from './routes/_authenticated/analysis'
import { Route as AuthenticatedBeyondAiRouteImport } from './routes/_authenticated/beyond-ai'
import { Route as AuthenticatedClassesRouteImport } from './routes/_authenticated/classes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFirstLoginRouteImport } from './routes/_authenticated/first-login'
import { Route as AuthenticatedLessonsRouteImport } from './routes/_authenticated/lessons'
import { Route as AuthenticatedNewsRouteImport } from './routes/_authenticated/news'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPracticeRouteImport } from './routes/_authenticated/practice'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedVocabRouteImport } from './routes/_authenticated/vocab'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminClassesRouteImport } from './routes/_authenticated/admin.classes'
import { Route as AuthenticatedAdminDailyRouteImport } from './routes/_authenticated/admin.daily'
import { Route as AuthenticatedAdminExamdatesRouteImport } from './routes/_authenticated/admin.examdates'
import { Route as AuthenticatedAdminHomepageRouteImport } from './routes/_authenticated/admin.homepage'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin.import'
import { Route as AuthenticatedAdminLessonsRouteImport } from './routes/_authenticated/admin.lessons'
import { Route as AuthenticatedAdminMocksRouteImport } from './routes/_authenticated/admin.mocks'
import { Route as AuthenticatedAdminNewsRouteImport } from './routes/_authenticated/admin.news'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminQuestionsRouteImport } from './routes/_authenticated/admin.questions'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminTestsRouteImport } from './routes/_authenticated/admin.tests'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminVocabRouteImport } from './routes/_authenticated/admin.vocab'
import { Route as AuthenticatedAnalysisIndexRouteImport } from './routes/_authenticated/analysis.index'
import { Route as AuthenticatedLessonsIndexRouteImport } from './routes/_authenticated/lessons.index'
import { Route as AuthenticatedLessonsSubjectSlugRouteImport } from './routes/_authenticated/lessons.$subjectSlug'
import { Route as AuthenticatedNewsIndexRouteImport } from './routes/_authenticated/news.index'
import { Route as AuthenticatedNewsSlugRouteImport } from './routes/_authenticated/news.$slug'
import { Route as AuthenticatedPracticeIndexRouteImport } from './routes/_authenticated/practice.index'
import { Route as AuthenticatedPracticeSectionRouteImport } from './routes/_authenticated/practice.$section'
import { Route as AuthenticatedPracticeDailyRouteImport } from './routes/_authenticated/practice.daily'
import { Route as AuthenticatedPracticeMockRouteImport } from './routes/_authenticated/practice.mock'
import { Route as AuthenticatedVocabIndexRouteImport } from './routes/_authenticated/vocab.index'
import { Route as AuthenticatedVocabDeckRouteImport } from './routes/_authenticated/vocab.deck'
import { Route as AuthenticatedVocabDecksRouteImport } from './routes/_authenticated/vocab.decks'
import { Route as AuthenticatedVocabTestsRouteImport } from './routes/_authenticated/vocab.tests'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin.users.index'
import { Route as AuthenticatedAdminUsersUserIdRouteImport } from './routes/_authenticated/admin.users.$userId'
import { Route as AuthenticatedAdminVocabIndexRouteImport } from './routes/_authenticated/admin.vocab.index'
import { Route as AuthenticatedAdminVocabAssignmentsRouteImport } from './routes/_authenticated/admin.vocab.assignments'
import { Route as AuthenticatedAdminVocabDecksRouteImport } from './routes/_authenticated/admin.vocab.decks'
import { Route as AuthenticatedAnalysisSessionIdRouteImport } from './routes/_authenticated/analysis.session.$id'
import { Route as AuthenticatedLessonsSubjectSlugIndexRouteImport } from './routes/_authenticated/lessons.$subjectSlug.index'
import { Route as AuthenticatedLessonsSubjectSlugTopicIdRouteImport } from './routes/_authenticated/lessons.$subjectSlug.$topicId'
import { Route as AuthenticatedPracticeSessionIdRouteImport } from './routes/_authenticated/practice.session.$id'
import { Route as AuthenticatedVocabDeckDeckIdRouteImport } from './routes/_authenticated/vocab.deck.$deckId'
import { Route as AuthenticatedVocabTestsIndexRouteImport } from './routes/_authenticated/vocab.tests.index'
import { Route as AuthenticatedVocabTestsIdRouteImport } from './routes/_authenticated/vocab.tests.$id'
import { Route as AuthenticatedAdminVocabDeckDeckIdRouteImport } from './routes/_authenticated/admin.vocab.deck.$deckId'
import { Route as AuthenticatedLessonsSubjectSlugTopicIdIndexRouteImport } from './routes/_authenticated/lessons.$subjectSlug.$topicId.index'
import { Route as AuthenticatedLessonsSubjectSlugTopicIdLessonIdRouteImport } from './routes/_authenticated/lessons.$subjectSlug.$topicId.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BannedRoute = BannedRouteImport.update({
  id: '/banned',
  path: '/banned',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalysisRoute = AuthenticatedAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBeyondAiRoute = AuthenticatedBeyondAiRouteImport.update({
  id: '/beyond-ai',
  path: '/beyond-ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassesRoute = AuthenticatedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFirstLoginRoute = AuthenticatedFirstLoginRouteImport.update({
  id: '/first-login',
  path: '/first-login',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLessonsRoute = AuthenticatedLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewsRoute = AuthenticatedNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPracticeRoute = AuthenticatedPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVocabRoute = AuthenticatedVocabRouteImport.update({
  id: '/vocab',
  path: '/vocab',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminClassesRoute =
  AuthenticatedAdminClassesRouteImport.update({
    id: '/classes',
    path: '/classes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDailyRoute = AuthenticatedAdminDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminExamdatesRoute =
  AuthenticatedAdminExamdatesRouteImport.update({
    id: '/examdates',
    path: '/examdates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHomepageRoute =
  AuthenticatedAdminHomepageRouteImport.update({
    id: '/homepage',
    path: '/homepage',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLessonsRoute =
  AuthenticatedAdminLessonsRouteImport.update({
    id: '/lessons',
    path: '/lessons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMocksRoute = AuthenticatedAdminMocksRouteImport.update({
  id: '/mocks',
  path: '/mocks',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminNewsRoute = AuthenticatedAdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQuestionsRoute =
  AuthenticatedAdminQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTestsRoute = AuthenticatedAdminTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminVocabRoute = AuthenticatedAdminVocabRouteImport.update({
  id: '/vocab',
  path: '/vocab',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAnalysisIndexRoute =
  AuthenticatedAnalysisIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAnalysisRoute,
  } as any)
const AuthenticatedLessonsIndexRoute =
  AuthenticatedLessonsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLessonsRoute,
  } as any)
const AuthenticatedLessonsSubjectSlugRoute =
  AuthenticatedLessonsSubjectSlugRouteImport.update({
    id: '/$subjectSlug',
    path: '/$subjectSlug',
    getParentRoute: () => AuthenticatedLessonsRoute,
  } as any)
const AuthenticatedNewsIndexRoute = AuthenticatedNewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedNewsRoute,
} as any)
const AuthenticatedNewsSlugRoute = AuthenticatedNewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthenticatedNewsRoute,
} as any)
const AuthenticatedPracticeIndexRoute =
  AuthenticatedPracticeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPracticeRoute,
  } as any)
const AuthenticatedPracticeSectionRoute =
  AuthenticatedPracticeSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => AuthenticatedPracticeRoute,
  } as any)
const AuthenticatedPracticeDailyRoute =
  AuthenticatedPracticeDailyRouteImport.update({
    id: '/daily',
    path: '/daily',
    getParentRoute: () => AuthenticatedPracticeRoute,
  } as any)
const AuthenticatedPracticeMockRoute =
  AuthenticatedPracticeMockRouteImport.update({
    id: '/mock',
    path: '/mock',
    getParentRoute: () => AuthenticatedPracticeRoute,
  } as any)
const AuthenticatedVocabIndexRoute = AuthenticatedVocabIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedVocabRoute,
} as any)
const AuthenticatedVocabDeckRoute = AuthenticatedVocabDeckRouteImport.update({
  id: '/deck',
  path: '/deck',
  getParentRoute: () => AuthenticatedVocabRoute,
} as any)
const AuthenticatedVocabDecksRoute = AuthenticatedVocabDecksRouteImport.update({
  id: '/decks',
  path: '/decks',
  getParentRoute: () => AuthenticatedVocabRoute,
} as any)
const AuthenticatedVocabTestsRoute = AuthenticatedVocabTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => AuthenticatedVocabRoute,
} as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)
const AuthenticatedAdminUsersUserIdRoute =
  AuthenticatedAdminUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)
const AuthenticatedAdminVocabIndexRoute =
  AuthenticatedAdminVocabIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminVocabRoute,
  } as any)
const AuthenticatedAdminVocabAssignmentsRoute =
  AuthenticatedAdminVocabAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedAdminVocabRoute,
  } as any)
const AuthenticatedAdminVocabDecksRoute =
  AuthenticatedAdminVocabDecksRouteImport.update({
    id: '/decks',
    path: '/decks',
    getParentRoute: () => AuthenticatedAdminVocabRoute,
  } as any)
const AuthenticatedAnalysisSessionIdRoute =
  AuthenticatedAnalysisSessionIdRouteImport.update({
    id: '/session/$id',
    path: '/session/$id',
    getParentRoute: () => AuthenticatedAnalysisRoute,
  } as any)
const AuthenticatedLessonsSubjectSlugIndexRoute =
  AuthenticatedLessonsSubjectSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLessonsSubjectSlugRoute,
  } as any)
const AuthenticatedLessonsSubjectSlugTopicIdRoute =
  AuthenticatedLessonsSubjectSlugTopicIdRouteImport.update({
    id: '/$topicId',
    path: '/$topicId',
    getParentRoute: () => AuthenticatedLessonsSubjectSlugRoute,
  } as any)
const AuthenticatedPracticeSessionIdRoute =
  AuthenticatedPracticeSessionIdRouteImport.update({
    id: '/session/$id',
    path: '/session/$id',
    getParentRoute: () => AuthenticatedPracticeRoute,
  } as any)
const AuthenticatedVocabDeckDeckIdRoute =
  AuthenticatedVocabDeckDeckIdRouteImport.update({
    id: '/$deckId',
    path: '/$deckId',
    getParentRoute: () => AuthenticatedVocabDeckRoute,
  } as any)
const AuthenticatedVocabTestsIndexRoute =
  AuthenticatedVocabTestsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedVocabTestsRoute,
  } as any)
const AuthenticatedVocabTestsIdRoute =
  AuthenticatedVocabTestsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedVocabTestsRoute,
  } as any)
const AuthenticatedAdminVocabDeckDeckIdRoute =
  AuthenticatedAdminVocabDeckDeckIdRouteImport.update({
    id: '/deck/$deckId',
    path: '/deck/$deckId',
    getParentRoute: () => AuthenticatedAdminVocabRoute,
  } as any)
const AuthenticatedLessonsSubjectSlugTopicIdIndexRoute =
  AuthenticatedLessonsSubjectSlugTopicIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLessonsSubjectSlugTopicIdRoute,
  } as any)
const AuthenticatedLessonsSubjectSlugTopicIdLessonIdRoute =
  AuthenticatedLessonsSubjectSlugTopicIdLessonIdRouteImport.update({
    id: '/$lessonId',
    path: '/$lessonId',
    getParentRoute: () => AuthenticatedLessonsSubjectSlugTopicIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/banned': typeof BannedRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/resources': typeof ResourcesRoute
  '/results': typeof ResultsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/analysis': typeof AuthenticatedAnalysisRouteWithChildren
  '/beyond-ai': typeof AuthenticatedBeyondAiRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/first-login': typeof AuthenticatedFirstLoginRoute
  '/lessons': typeof AuthenticatedLessonsRouteWithChildren
  '/news': typeof AuthenticatedNewsRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/practice': typeof AuthenticatedPracticeRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/vocab': typeof AuthenticatedVocabRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/classes': typeof AuthenticatedAdminClassesRoute
  '/admin/daily': typeof AuthenticatedAdminDailyRoute
  '/admin/examdates': typeof AuthenticatedAdminExamdatesRoute
  '/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/lessons': typeof AuthenticatedAdminLessonsRoute
  '/admin/mocks': typeof AuthenticatedAdminMocksRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/tests': typeof AuthenticatedAdminTestsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/admin/vocab': typeof AuthenticatedAdminVocabRouteWithChildren
  '/lessons/$subjectSlug': typeof AuthenticatedLessonsSubjectSlugRouteWithChildren
  '/news/$slug': typeof AuthenticatedNewsSlugRoute
  '/practice/$section': typeof AuthenticatedPracticeSectionRoute
  '/practice/daily': typeof AuthenticatedPracticeDailyRoute
  '/practice/mock': typeof AuthenticatedPracticeMockRoute
  '/vocab/deck': typeof AuthenticatedVocabDeckRouteWithChildren
  '/vocab/decks': typeof AuthenticatedVocabDecksRoute
  '/vocab/tests': typeof AuthenticatedVocabTestsRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/analysis/': typeof AuthenticatedAnalysisIndexRoute
  '/lessons/': typeof AuthenticatedLessonsIndexRoute
  '/news/': typeof AuthenticatedNewsIndexRoute
  '/practice/': typeof AuthenticatedPracticeIndexRoute
  '/vocab/': typeof AuthenticatedVocabIndexRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/admin/vocab/assignments': typeof AuthenticatedAdminVocabAssignmentsRoute
  '/admin/vocab/decks': typeof AuthenticatedAdminVocabDecksRoute
  '/analysis/session/$id': typeof AuthenticatedAnalysisSessionIdRoute
  '/lessons/$subjectSlug/$topicId': typeof AuthenticatedLessonsSubjectSlugTopicIdRouteWithChildren
  '/practice/session/$id': typeof AuthenticatedPracticeSessionIdRoute
  '/vocab/deck/$deckId': typeof AuthenticatedVocabDeckDeckIdRoute
  '/vocab/tests/$id': typeof AuthenticatedVocabTestsIdRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/admin/vocab/': typeof AuthenticatedAdminVocabIndexRoute
  '/lessons/$subjectSlug/': typeof AuthenticatedLessonsSubjectSlugIndexRoute
  '/vocab/tests/': typeof AuthenticatedVocabTestsIndexRoute
  '/admin/vocab/deck/$deckId': typeof AuthenticatedAdminVocabDeckDeckIdRoute
  '/lessons/$subjectSlug/$topicId/$lessonId': typeof AuthenticatedLessonsSubjectSlugTopicIdLessonIdRoute
  '/lessons/$subjectSlug/$topicId/': typeof AuthenticatedLessonsSubjectSlugTopicIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/banned': typeof BannedRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/resources': typeof ResourcesRoute
  '/results': typeof ResultsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/beyond-ai': typeof AuthenticatedBeyondAiRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/first-login': typeof AuthenticatedFirstLoginRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/classes': typeof AuthenticatedAdminClassesRoute
  '/admin/daily': typeof AuthenticatedAdminDailyRoute
  '/admin/examdates': typeof AuthenticatedAdminExamdatesRoute
  '/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/lessons': typeof AuthenticatedAdminLessonsRoute
  '/admin/mocks': typeof AuthenticatedAdminMocksRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/tests': typeof AuthenticatedAdminTestsRoute
  '/news/$slug': typeof AuthenticatedNewsSlugRoute
  '/practice/$section': typeof AuthenticatedPracticeSectionRoute
  '/practice/daily': typeof AuthenticatedPracticeDailyRoute
  '/practice/mock': typeof AuthenticatedPracticeMockRoute
  '/vocab/deck': typeof AuthenticatedVocabDeckRouteWithChildren
  '/vocab/decks': typeof AuthenticatedVocabDecksRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/analysis': typeof AuthenticatedAnalysisIndexRoute
  '/lessons': typeof AuthenticatedLessonsIndexRoute
  '/news': typeof AuthenticatedNewsIndexRoute
  '/practice': typeof AuthenticatedPracticeIndexRoute
  '/vocab': typeof AuthenticatedVocabIndexRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/admin/vocab/assignments': typeof AuthenticatedAdminVocabAssignmentsRoute
  '/admin/vocab/decks': typeof AuthenticatedAdminVocabDecksRoute
  '/analysis/session/$id': typeof AuthenticatedAnalysisSessionIdRoute
  '/practice/session/$id': typeof AuthenticatedPracticeSessionIdRoute
  '/vocab/deck/$deckId': typeof AuthenticatedVocabDeckDeckIdRoute
  '/vocab/tests/$id': typeof AuthenticatedVocabTestsIdRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/admin/vocab': typeof AuthenticatedAdminVocabIndexRoute
  '/lessons/$subjectSlug': typeof AuthenticatedLessonsSubjectSlugIndexRoute
  '/vocab/tests': typeof AuthenticatedVocabTestsIndexRoute
  '/admin/vocab/deck/$deckId': typeof AuthenticatedAdminVocabDeckDeckIdRoute
  '/lessons/$subjectSlug/$topicId/$lessonId': typeof AuthenticatedLessonsSubjectSlugTopicIdLessonIdRoute
  '/lessons/$subjectSlug/$topicId': typeof AuthenticatedLessonsSubjectSlugTopicIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/banned': typeof BannedRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/resources': typeof ResourcesRoute
  '/results': typeof ResultsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/analysis': typeof AuthenticatedAnalysisRouteWithChildren
  '/_authenticated/beyond-ai': typeof AuthenticatedBeyondAiRoute
  '/_authenticated/classes': typeof AuthenticatedClassesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/first-login': typeof AuthenticatedFirstLoginRoute
  '/_authenticated/lessons': typeof AuthenticatedLessonsRouteWithChildren
  '/_authenticated/news': typeof AuthenticatedNewsRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/practice': typeof AuthenticatedPracticeRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/vocab': typeof AuthenticatedVocabRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/admin/classes': typeof AuthenticatedAdminClassesRoute
  '/_authenticated/admin/daily': typeof AuthenticatedAdminDailyRoute
  '/_authenticated/admin/examdates': typeof AuthenticatedAdminExamdatesRoute
  '/_authenticated/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/lessons': typeof AuthenticatedAdminLessonsRoute
  '/_authenticated/admin/mocks': typeof AuthenticatedAdminMocksRoute
  '/_authenticated/admin/news': typeof AuthenticatedAdminNewsRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/tests': typeof AuthenticatedAdminTestsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/_authenticated/admin/vocab': typeof AuthenticatedAdminVocabRouteWithChildren
  '/_authenticated/lessons/$subjectSlug': typeof AuthenticatedLessonsSubjectSlugRouteWithChildren
  '/_authenticated/news/$slug': typeof AuthenticatedNewsSlugRoute
  '/_authenticated/practice/$section': typeof AuthenticatedPracticeSectionRoute
  '/_authenticated/practice/daily': typeof AuthenticatedPracticeDailyRoute
  '/_authenticated/practice/mock': typeof AuthenticatedPracticeMockRoute
  '/_authenticated/vocab/deck': typeof AuthenticatedVocabDeckRouteWithChildren
  '/_authenticated/vocab/decks': typeof AuthenticatedVocabDecksRoute
  '/_authenticated/vocab/tests': typeof AuthenticatedVocabTestsRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/analysis/': typeof AuthenticatedAnalysisIndexRoute
  '/_authenticated/lessons/': typeof AuthenticatedLessonsIndexRoute
  '/_authenticated/news/': typeof AuthenticatedNewsIndexRoute
  '/_authenticated/practice/': typeof AuthenticatedPracticeIndexRoute
  '/_authenticated/vocab/': typeof AuthenticatedVocabIndexRoute
  '/_authenticated/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/_authenticated/admin/vocab/assignments': typeof AuthenticatedAdminVocabAssignmentsRoute
  '/_authenticated/admin/vocab/decks': typeof AuthenticatedAdminVocabDecksRoute
  '/_authenticated/analysis/session/$id': typeof AuthenticatedAnalysisSessionIdRoute
  '/_authenticated/lessons/$subjectSlug/$topicId': typeof AuthenticatedLessonsSubjectSlugTopicIdRouteWithChildren
  '/_authenticated/practice/session/$id': typeof AuthenticatedPracticeSessionIdRoute
  '/_authenticated/vocab/deck/$deckId': typeof AuthenticatedVocabDeckDeckIdRoute
  '/_authenticated/vocab/tests/$id': typeof AuthenticatedVocabTestsIdRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/admin/vocab/': typeof AuthenticatedAdminVocabIndexRoute
  '/_authenticated/lessons/$subjectSlug/': typeof AuthenticatedLessonsSubjectSlugIndexRoute
  '/_authenticated/vocab/tests/': typeof AuthenticatedVocabTestsIndexRoute
  '/_authenticated/admin/vocab/deck/$deckId': typeof AuthenticatedAdminVocabDeckDeckIdRoute
  '/_authenticated/lessons/$subjectSlug/$topicId/$lessonId': typeof AuthenticatedLessonsSubjectSlugTopicIdLessonIdRoute
  '/_authenticated/lessons/$subjectSlug/$topicId/': typeof AuthenticatedLessonsSubjectSlugTopicIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/banned'
    | '/privacy'
    | '/programs'
    | '/resources'
    | '/results'
    | '/signin'
    | '/signup'
    | '/support'
    | '/terms'
    | '/admin'
    | '/analysis'
    | '/beyond-ai'
    | '/classes'
    | '/dashboard'
    | '/first-login'
    | '/lessons'
    | '/news'
    | '/onboarding'
    | '/practice'
    | '/profile'
    | '/vocab'
    | '/auth/callback'
    | '/admin/classes'
    | '/admin/daily'
    | '/admin/examdates'
    | '/admin/homepage'
    | '/admin/import'
    | '/admin/lessons'
    | '/admin/mocks'
    | '/admin/news'
    | '/admin/notifications'
    | '/admin/questions'
    | '/admin/settings'
    | '/admin/tests'
    | '/admin/users'
    | '/admin/vocab'
    | '/lessons/$subjectSlug'
    | '/news/$slug'
    | '/practice/$section'
    | '/practice/daily'
    | '/practice/mock'
    | '/vocab/deck'
    | '/vocab/decks'
    | '/vocab/tests'
    | '/admin/'
    | '/analysis/'
    | '/lessons/'
    | '/news/'
    | '/practice/'
    | '/vocab/'
    | '/admin/users/$userId'
    | '/admin/vocab/assignments'
    | '/admin/vocab/decks'
    | '/analysis/session/$id'
    | '/lessons/$subjectSlug/$topicId'
    | '/practice/session/$id'
    | '/vocab/deck/$deckId'
    | '/vocab/tests/$id'
    | '/admin/users/'
    | '/admin/vocab/'
    | '/lessons/$subjectSlug/'
    | '/vocab/tests/'
    | '/admin/vocab/deck/$deckId'
    | '/lessons/$subjectSlug/$topicId/$lessonId'
    | '/lessons/$subjectSlug/$topicId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/banned'
    | '/privacy'
    | '/programs'
    | '/resources'
    | '/results'
    | '/signin'
    | '/signup'
    | '/support'
    | '/terms'
    | '/beyond-ai'
    | '/classes'
    | '/dashboard'
    | '/first-login'
    | '/onboarding'
    | '/profile'
    | '/auth/callback'
    | '/admin/classes'
    | '/admin/daily'
    | '/admin/examdates'
    | '/admin/homepage'
    | '/admin/import'
    | '/admin/lessons'
    | '/admin/mocks'
    | '/admin/news'
    | '/admin/notifications'
    | '/admin/questions'
    | '/admin/settings'
    | '/admin/tests'
    | '/news/$slug'
    | '/practice/$section'
    | '/practice/daily'
    | '/practice/mock'
    | '/vocab/deck'
    | '/vocab/decks'
    | '/admin'
    | '/analysis'
    | '/lessons'
    | '/news'
    | '/practice'
    | '/vocab'
    | '/admin/users/$userId'
    | '/admin/vocab/assignments'
    | '/admin/vocab/decks'
    | '/analysis/session/$id'
    | '/practice/session/$id'
    | '/vocab/deck/$deckId'
    | '/vocab/tests/$id'
    | '/admin/users'
    | '/admin/vocab'
    | '/lessons/$subjectSlug'
    | '/vocab/tests'
    | '/admin/vocab/deck/$deckId'
    | '/lessons/$subjectSlug/$topicId/$lessonId'
    | '/lessons/$subjectSlug/$topicId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/banned'
    | '/privacy'
    | '/programs'
    | '/resources'
    | '/results'
    | '/signin'
    | '/signup'
    | '/support'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/analysis'
    | '/_authenticated/beyond-ai'
    | '/_authenticated/classes'
    | '/_authenticated/dashboard'
    | '/_authenticated/first-login'
    | '/_authenticated/lessons'
    | '/_authenticated/news'
    | '/_authenticated/onboarding'
    | '/_authenticated/practice'
    | '/_authenticated/profile'
    | '/_authenticated/vocab'
    | '/auth/callback'
    | '/_authenticated/admin/classes'
    | '/_authenticated/admin/daily'
    | '/_authenticated/admin/examdates'
    | '/_authenticated/admin/homepage'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/lessons'
    | '/_authenticated/admin/mocks'
    | '/_authenticated/admin/news'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/questions'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/tests'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/vocab'
    | '/_authenticated/lessons/$subjectSlug'
    | '/_authenticated/news/$slug'
    | '/_authenticated/practice/$section'
    | '/_authenticated/practice/daily'
    | '/_authenticated/practice/mock'
    | '/_authenticated/vocab/deck'
    | '/_authenticated/vocab/decks'
    | '/_authenticated/vocab/tests'
    | '/_authenticated/admin/'
    | '/_authenticated/analysis/'
    | '/_authenticated/lessons/'
    | '/_authenticated/news/'
    | '/_authenticated/practice/'
    | '/_authenticated/vocab/'
    | '/_authenticated/admin/users/$userId'
    | '/_authenticated/admin/vocab/assignments'
    | '/_authenticated/admin/vocab/decks'
    | '/_authenticated/analysis/session/$id'
    | '/_authenticated/lessons/$subjectSlug/$topicId'
    | '/_authenticated/practice/session/$id'
    | '/_authenticated/vocab/deck/$deckId'
    | '/_authenticated/vocab/tests/$id'
    | '/_authenticated/admin/users/'
    | '/_authenticated/admin/vocab/'
    | '/_authenticated/lessons/$subjectSlug/'
    | '/_authenticated/vocab/tests/'
    | '/_authenticated/admin/vocab/deck/$deckId'
    | '/_authenticated/lessons/$subjectSlug/$topicId/$lessonId'
    | '/_authenticated/lessons/$subjectSlug/$topicId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  BannedRoute: typeof BannedRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgramsRoute: typeof ProgramsRoute
  ResourcesRoute: typeof ResourcesRoute
  ResultsRoute: typeof ResultsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banned': {
      id: '/banned'
      path: '/banned'
      fullPath: '/banned'
      preLoaderRoute: typeof BannedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analysis': {
      id: '/_authenticated/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AuthenticatedAnalysisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/beyond-ai': {
      id: '/_authenticated/beyond-ai'
      path: '/beyond-ai'
      fullPath: '/beyond-ai'
      preLoaderRoute: typeof AuthenticatedBeyondAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes': {
      id: '/_authenticated/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/first-login': {
      id: '/_authenticated/first-login'
      path: '/first-login'
      fullPath: '/first-login'
      preLoaderRoute: typeof AuthenticatedFirstLoginRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lessons': {
      id: '/_authenticated/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof AuthenticatedLessonsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/news': {
      id: '/_authenticated/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AuthenticatedNewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice': {
      id: '/_authenticated/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AuthenticatedPracticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vocab': {
      id: '/_authenticated/vocab'
      path: '/vocab'
      fullPath: '/vocab'
      preLoaderRoute: typeof AuthenticatedVocabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/classes': {
      id: '/_authenticated/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AuthenticatedAdminClassesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/daily': {
      id: '/_authenticated/admin/daily'
      path: '/daily'
      fullPath: '/admin/daily'
      preLoaderRoute: typeof AuthenticatedAdminDailyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/examdates': {
      id: '/_authenticated/admin/examdates'
      path: '/examdates'
      fullPath: '/admin/examdates'
      preLoaderRoute: typeof AuthenticatedAdminExamdatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/homepage': {
      id: '/_authenticated/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AuthenticatedAdminHomepageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/lessons': {
      id: '/_authenticated/admin/lessons'
      path: '/lessons'
      fullPath: '/admin/lessons'
      preLoaderRoute: typeof AuthenticatedAdminLessonsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/mocks': {
      id: '/_authenticated/admin/mocks'
      path: '/mocks'
      fullPath: '/admin/mocks'
      preLoaderRoute: typeof AuthenticatedAdminMocksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/news': {
      id: '/_authenticated/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AuthenticatedAdminNewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/questions': {
      id: '/_authenticated/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AuthenticatedAdminQuestionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tests': {
      id: '/_authenticated/admin/tests'
      path: '/tests'
      fullPath: '/admin/tests'
      preLoaderRoute: typeof AuthenticatedAdminTestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/vocab': {
      id: '/_authenticated/admin/vocab'
      path: '/vocab'
      fullPath: '/admin/vocab'
      preLoaderRoute: typeof AuthenticatedAdminVocabRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/analysis/': {
      id: '/_authenticated/analysis/'
      path: '/'
      fullPath: '/analysis/'
      preLoaderRoute: typeof AuthenticatedAnalysisIndexRouteImport
      parentRoute: typeof AuthenticatedAnalysisRoute
    }
    '/_authenticated/lessons/': {
      id: '/_authenticated/lessons/'
      path: '/'
      fullPath: '/lessons/'
      preLoaderRoute: typeof AuthenticatedLessonsIndexRouteImport
      parentRoute: typeof AuthenticatedLessonsRoute
    }
    '/_authenticated/lessons/$subjectSlug': {
      id: '/_authenticated/lessons/$subjectSlug'
      path: '/$subjectSlug'
      fullPath: '/lessons/$subjectSlug'
      preLoaderRoute: typeof AuthenticatedLessonsSubjectSlugRouteImport
      parentRoute: typeof AuthenticatedLessonsRoute
    }
    '/_authenticated/news/': {
      id: '/_authenticated/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof AuthenticatedNewsIndexRouteImport
      parentRoute: typeof AuthenticatedNewsRoute
    }
    '/_authenticated/news/$slug': {
      id: '/_authenticated/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof AuthenticatedNewsSlugRouteImport
      parentRoute: typeof AuthenticatedNewsRoute
    }
    '/_authenticated/practice/': {
      id: '/_authenticated/practice/'
      path: '/'
      fullPath: '/practice/'
      preLoaderRoute: typeof AuthenticatedPracticeIndexRouteImport
      parentRoute: typeof AuthenticatedPracticeRoute
    }
    '/_authenticated/practice/$section': {
      id: '/_authenticated/practice/$section'
      path: '/$section'
      fullPath: '/practice/$section'
      preLoaderRoute: typeof AuthenticatedPracticeSectionRouteImport
      parentRoute: typeof AuthenticatedPracticeRoute
    }
    '/_authenticated/practice/daily': {
      id: '/_authenticated/practice/daily'
      path: '/daily'
      fullPath: '/practice/daily'
      preLoaderRoute: typeof AuthenticatedPracticeDailyRouteImport
      parentRoute: typeof AuthenticatedPracticeRoute
    }
    '/_authenticated/practice/mock': {
      id: '/_authenticated/practice/mock'
      path: '/mock'
      fullPath: '/practice/mock'
      preLoaderRoute: typeof AuthenticatedPracticeMockRouteImport
      parentRoute: typeof AuthenticatedPracticeRoute
    }
    '/_authenticated/vocab/': {
      id: '/_authenticated/vocab/'
      path: '/'
      fullPath: '/vocab/'
      preLoaderRoute: typeof AuthenticatedVocabIndexRouteImport
      parentRoute: typeof AuthenticatedVocabRoute
    }
    '/_authenticated/vocab/deck': {
      id: '/_authenticated/vocab/deck'
      path: '/deck'
      fullPath: '/vocab/deck'
      preLoaderRoute: typeof AuthenticatedVocabDeckRouteImport
      parentRoute: typeof AuthenticatedVocabRoute
    }
    '/_authenticated/vocab/decks': {
      id: '/_authenticated/vocab/decks'
      path: '/decks'
      fullPath: '/vocab/decks'
      preLoaderRoute: typeof AuthenticatedVocabDecksRouteImport
      parentRoute: typeof AuthenticatedVocabRoute
    }
    '/_authenticated/vocab/tests': {
      id: '/_authenticated/vocab/tests'
      path: '/tests'
      fullPath: '/vocab/tests'
      preLoaderRoute: typeof AuthenticatedVocabTestsRouteImport
      parentRoute: typeof AuthenticatedVocabRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
    '/_authenticated/admin/users/$userId': {
      id: '/_authenticated/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
    '/_authenticated/admin/vocab/': {
      id: '/_authenticated/admin/vocab/'
      path: '/'
      fullPath: '/admin/vocab/'
      preLoaderRoute: typeof AuthenticatedAdminVocabIndexRouteImport
      parentRoute: typeof AuthenticatedAdminVocabRoute
    }
    '/_authenticated/admin/vocab/assignments': {
      id: '/_authenticated/admin/vocab/assignments'
      path: '/assignments'
      fullPath: '/admin/vocab/assignments'
      preLoaderRoute: typeof AuthenticatedAdminVocabAssignmentsRouteImport
      parentRoute: typeof AuthenticatedAdminVocabRoute
    }
    '/_authenticated/admin/vocab/decks': {
      id: '/_authenticated/admin/vocab/decks'
      path: '/decks'
      fullPath: '/admin/vocab/decks'
      preLoaderRoute: typeof AuthenticatedAdminVocabDecksRouteImport
      parentRoute: typeof AuthenticatedAdminVocabRoute
    }
    '/_authenticated/analysis/session/$id': {
      id: '/_authenticated/analysis/session/$id'
      path: '/session/$id'
      fullPath: '/analysis/session/$id'
      preLoaderRoute: typeof AuthenticatedAnalysisSessionIdRouteImport
      parentRoute: typeof AuthenticatedAnalysisRoute
    }
    '/_authenticated/lessons/$subjectSlug/': {
      id: '/_authenticated/lessons/$subjectSlug/'
      path: '/'
      fullPath: '/lessons/$subjectSlug/'
      preLoaderRoute: typeof AuthenticatedLessonsSubjectSlugIndexRouteImport
      parentRoute: typeof AuthenticatedLessonsSubjectSlugRoute
    }
    '/_authenticated/lessons/$subjectSlug/$topicId': {
      id: '/_authenticated/lessons/$subjectSlug/$topicId'
      path: '/$topicId'
      fullPath: '/lessons/$subjectSlug/$topicId'
      preLoaderRoute: typeof AuthenticatedLessonsSubjectSlugTopicIdRouteImport
      parentRoute: typeof AuthenticatedLessonsSubjectSlugRoute
    }
    '/_authenticated/practice/session/$id': {
      id: '/_authenticated/practice/session/$id'
      path: '/session/$id'
      fullPath: '/practice/session/$id'
      preLoaderRoute: typeof AuthenticatedPracticeSessionIdRouteImport
      parentRoute: typeof AuthenticatedPracticeRoute
    }
    '/_authenticated/vocab/deck/$deckId': {
      id: '/_authenticated/vocab/deck/$deckId'
      path: '/$deckId'
      fullPath: '/vocab/deck/$deckId'
      preLoaderRoute: typeof AuthenticatedVocabDeckDeckIdRouteImport
      parentRoute: typeof AuthenticatedVocabDeckRoute
    }
    '/_authenticated/vocab/tests/': {
      id: '/_authenticated/vocab/tests/'
      path: '/'
      fullPath: '/vocab/tests/'
      preLoaderRoute: typeof AuthenticatedVocabTestsIndexRouteImport
      parentRoute: typeof AuthenticatedVocabTestsRoute
    }
    '/_authenticated/vocab/tests/$id': {
      id: '/_authenticated/vocab/tests/$id'
      path: '/$id'
      fullPath: '/vocab/tests/$id'
      preLoaderRoute: typeof AuthenticatedVocabTestsIdRouteImport
      parentRoute: typeof AuthenticatedVocabTestsRoute
    }
    '/_authenticated/admin/vocab/deck/$deckId': {
      id: '/_authenticated/admin/vocab/deck/$deckId'
      path: '/deck/$deckId'
      fullPath: '/admin/vocab/deck/$deckId'
      preLoaderRoute: typeof AuthenticatedAdminVocabDeckDeckIdRouteImport
      parentRoute: typeof AuthenticatedAdminVocabRoute
    }
    '/_authenticated/lessons/$subjectSlug/$topicId/': {
      id: '/_authenticated/lessons/$subjectSlug/$topicId/'
      path: '/'
      fullPath: '/lessons/$subjectSlug/$topicId/'
      preLoaderRoute: typeof AuthenticatedLessonsSubjectSlugTopicIdIndexRouteImport
      parentRoute: typeof AuthenticatedLessonsSubjectSlugTopicIdRoute
    }
    '/_authenticated/lessons/$subjectSlug/$topicId/$lessonId': {
      id: '/_authenticated/lessons/$subjectSlug/$topicId/$lessonId'
      path: '/$lessonId'
      fullPath: '/lessons/$subjectSlug/$topicId/$lessonId'
      preLoaderRoute: typeof AuthenticatedLessonsSubjectSlugTopicIdLessonIdRouteImport
      parentRoute: typeof AuthenticatedLessonsSubjectSlugTopicIdRoute
    }
  }
}

interface AuthenticatedAdminUsersRouteChildren {
  AuthenticatedAdminUsersUserIdRoute: typeof AuthenticatedAdminUsersUserIdRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminUsersRouteChildren: AuthenticatedAdminUsersRouteChildren =
  {
    AuthenticatedAdminUsersUserIdRoute: AuthenticatedAdminUsersUserIdRoute,
    AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
  }

const AuthenticatedAdminUsersRouteWithChildren =
  AuthenticatedAdminUsersRoute._addFileChildren(
    AuthenticatedAdminUsersRouteChildren,
  )

interface AuthenticatedAdminVocabRouteChildren {
  AuthenticatedAdminVocabAssignmentsRoute: typeof AuthenticatedAdminVocabAssignmentsRoute
  AuthenticatedAdminVocabDecksRoute: typeof AuthenticatedAdminVocabDecksRoute
  AuthenticatedAdminVocabIndexRoute: typeof AuthenticatedAdminVocabIndexRoute
  AuthenticatedAdminVocabDeckDeckIdRoute: typeof AuthenticatedAdminVocabDeckDeckIdRoute
}

const AuthenticatedAdminVocabRouteChildren: AuthenticatedAdminVocabRouteChildren =
  {
    AuthenticatedAdminVocabAssignmentsRoute:
      AuthenticatedAdminVocabAssignmentsRoute,
    AuthenticatedAdminVocabDecksRoute: AuthenticatedAdminVocabDecksRoute,
    AuthenticatedAdminVocabIndexRoute: AuthenticatedAdminVocabIndexRoute,
    AuthenticatedAdminVocabDeckDeckIdRoute:
      AuthenticatedAdminVocabDeckDeckIdRoute,
  }

const AuthenticatedAdminVocabRouteWithChildren =
  AuthenticatedAdminVocabRoute._addFileChildren(
    AuthenticatedAdminVocabRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminClassesRoute: typeof AuthenticatedAdminClassesRoute
  AuthenticatedAdminDailyRoute: typeof AuthenticatedAdminDailyRoute
  AuthenticatedAdminExamdatesRoute: typeof AuthenticatedAdminExamdatesRoute
  AuthenticatedAdminHomepageRoute: typeof AuthenticatedAdminHomepageRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminLessonsRoute: typeof AuthenticatedAdminLessonsRoute
  AuthenticatedAdminMocksRoute: typeof AuthenticatedAdminMocksRoute
  AuthenticatedAdminNewsRoute: typeof AuthenticatedAdminNewsRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminQuestionsRoute: typeof AuthenticatedAdminQuestionsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTestsRoute: typeof AuthenticatedAdminTestsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRouteWithChildren
  AuthenticatedAdminVocabRoute: typeof AuthenticatedAdminVocabRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminClassesRoute: AuthenticatedAdminClassesRoute,
  AuthenticatedAdminDailyRoute: AuthenticatedAdminDailyRoute,
  AuthenticatedAdminExamdatesRoute: AuthenticatedAdminExamdatesRoute,
  AuthenticatedAdminHomepageRoute: AuthenticatedAdminHomepageRoute,
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminLessonsRoute: AuthenticatedAdminLessonsRoute,
  AuthenticatedAdminMocksRoute: AuthenticatedAdminMocksRoute,
  AuthenticatedAdminNewsRoute: AuthenticatedAdminNewsRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminQuestionsRoute: AuthenticatedAdminQuestionsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTestsRoute: AuthenticatedAdminTestsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRouteWithChildren,
  AuthenticatedAdminVocabRoute: AuthenticatedAdminVocabRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAnalysisRouteChildren {
  AuthenticatedAnalysisIndexRoute: typeof AuthenticatedAnalysisIndexRoute
  AuthenticatedAnalysisSessionIdRoute: typeof AuthenticatedAnalysisSessionIdRoute
}

const AuthenticatedAnalysisRouteChildren: AuthenticatedAnalysisRouteChildren = {
  AuthenticatedAnalysisIndexRoute: AuthenticatedAnalysisIndexRoute,
  AuthenticatedAnalysisSessionIdRoute: AuthenticatedAnalysisSessionIdRoute,
}

const AuthenticatedAnalysisRouteWithChildren =
  AuthenticatedAnalysisRoute._addFileChildren(
    AuthenticatedAnalysisRouteChildren,
  )

interface AuthenticatedLessonsSubjectSlugTopicIdRouteChildren {
  AuthenticatedLessonsSubjectSlugTopicIdLessonIdRoute: typeof AuthenticatedLessonsSubjectSlugTopicIdLessonIdRoute
  AuthenticatedLessonsSubjectSlugTopicIdIndexRoute: typeof AuthenticatedLessonsSubjectSlugTopicIdIndexRoute
}

const AuthenticatedLessonsSubjectSlugTopicIdRouteChildren: AuthenticatedLessonsSubjectSlugTopicIdRouteChildren =
  {
    AuthenticatedLessonsSubjectSlugTopicIdLessonIdRoute:
      AuthenticatedLessonsSubjectSlugTopicIdLessonIdRoute,
    AuthenticatedLessonsSubjectSlugTopicIdIndexRoute:
      AuthenticatedLessonsSubjectSlugTopicIdIndexRoute,
  }

const AuthenticatedLessonsSubjectSlugTopicIdRouteWithChildren =
  AuthenticatedLessonsSubjectSlugTopicIdRoute._addFileChildren(
    AuthenticatedLessonsSubjectSlugTopicIdRouteChildren,
  )

interface AuthenticatedLessonsSubjectSlugRouteChildren {
  AuthenticatedLessonsSubjectSlugTopicIdRoute: typeof AuthenticatedLessonsSubjectSlugTopicIdRouteWithChildren
  AuthenticatedLessonsSubjectSlugIndexRoute: typeof AuthenticatedLessonsSubjectSlugIndexRoute
}

const AuthenticatedLessonsSubjectSlugRouteChildren: AuthenticatedLessonsSubjectSlugRouteChildren =
  {
    AuthenticatedLessonsSubjectSlugTopicIdRoute:
      AuthenticatedLessonsSubjectSlugTopicIdRouteWithChildren,
    AuthenticatedLessonsSubjectSlugIndexRoute:
      AuthenticatedLessonsSubjectSlugIndexRoute,
  }

const AuthenticatedLessonsSubjectSlugRouteWithChildren =
  AuthenticatedLessonsSubjectSlugRoute._addFileChildren(
    AuthenticatedLessonsSubjectSlugRouteChildren,
  )

interface AuthenticatedLessonsRouteChildren {
  AuthenticatedLessonsSubjectSlugRoute: typeof AuthenticatedLessonsSubjectSlugRouteWithChildren
  AuthenticatedLessonsIndexRoute: typeof AuthenticatedLessonsIndexRoute
}

const AuthenticatedLessonsRouteChildren: AuthenticatedLessonsRouteChildren = {
  AuthenticatedLessonsSubjectSlugRoute:
    AuthenticatedLessonsSubjectSlugRouteWithChildren,
  AuthenticatedLessonsIndexRoute: AuthenticatedLessonsIndexRoute,
}

const AuthenticatedLessonsRouteWithChildren =
  AuthenticatedLessonsRoute._addFileChildren(AuthenticatedLessonsRouteChildren)

interface AuthenticatedNewsRouteChildren {
  AuthenticatedNewsSlugRoute: typeof AuthenticatedNewsSlugRoute
  AuthenticatedNewsIndexRoute: typeof AuthenticatedNewsIndexRoute
}

const AuthenticatedNewsRouteChildren: AuthenticatedNewsRouteChildren = {
  AuthenticatedNewsSlugRoute: AuthenticatedNewsSlugRoute,
  AuthenticatedNewsIndexRoute: AuthenticatedNewsIndexRoute,
}

const AuthenticatedNewsRouteWithChildren =
  AuthenticatedNewsRoute._addFileChildren(AuthenticatedNewsRouteChildren)

interface AuthenticatedPracticeRouteChildren {
  AuthenticatedPracticeSectionRoute: typeof AuthenticatedPracticeSectionRoute
  AuthenticatedPracticeDailyRoute: typeof AuthenticatedPracticeDailyRoute
  AuthenticatedPracticeMockRoute: typeof AuthenticatedPracticeMockRoute
  AuthenticatedPracticeIndexRoute: typeof AuthenticatedPracticeIndexRoute
  AuthenticatedPracticeSessionIdRoute: typeof AuthenticatedPracticeSessionIdRoute
}

const AuthenticatedPracticeRouteChildren: AuthenticatedPracticeRouteChildren = {
  AuthenticatedPracticeSectionRoute: AuthenticatedPracticeSectionRoute,
  AuthenticatedPracticeDailyRoute: AuthenticatedPracticeDailyRoute,
  AuthenticatedPracticeMockRoute: AuthenticatedPracticeMockRoute,
  AuthenticatedPracticeIndexRoute: AuthenticatedPracticeIndexRoute,
  AuthenticatedPracticeSessionIdRoute: AuthenticatedPracticeSessionIdRoute,
}

const AuthenticatedPracticeRouteWithChildren =
  AuthenticatedPracticeRoute._addFileChildren(
    AuthenticatedPracticeRouteChildren,
  )

interface AuthenticatedVocabDeckRouteChildren {
  AuthenticatedVocabDeckDeckIdRoute: typeof AuthenticatedVocabDeckDeckIdRoute
}

const AuthenticatedVocabDeckRouteChildren: AuthenticatedVocabDeckRouteChildren =
  {
    AuthenticatedVocabDeckDeckIdRoute: AuthenticatedVocabDeckDeckIdRoute,
  }

const AuthenticatedVocabDeckRouteWithChildren =
  AuthenticatedVocabDeckRoute._addFileChildren(
    AuthenticatedVocabDeckRouteChildren,
  )

interface AuthenticatedVocabTestsRouteChildren {
  AuthenticatedVocabTestsIdRoute: typeof AuthenticatedVocabTestsIdRoute
  AuthenticatedVocabTestsIndexRoute: typeof AuthenticatedVocabTestsIndexRoute
}

const AuthenticatedVocabTestsRouteChildren: AuthenticatedVocabTestsRouteChildren =
  {
    AuthenticatedVocabTestsIdRoute: AuthenticatedVocabTestsIdRoute,
    AuthenticatedVocabTestsIndexRoute: AuthenticatedVocabTestsIndexRoute,
  }

const AuthenticatedVocabTestsRouteWithChildren =
  AuthenticatedVocabTestsRoute._addFileChildren(
    AuthenticatedVocabTestsRouteChildren,
  )

interface AuthenticatedVocabRouteChildren {
  AuthenticatedVocabDeckRoute: typeof AuthenticatedVocabDeckRouteWithChildren
  AuthenticatedVocabDecksRoute: typeof AuthenticatedVocabDecksRoute
  AuthenticatedVocabTestsRoute: typeof AuthenticatedVocabTestsRouteWithChildren
  AuthenticatedVocabIndexRoute: typeof AuthenticatedVocabIndexRoute
}

const AuthenticatedVocabRouteChildren: AuthenticatedVocabRouteChildren = {
  AuthenticatedVocabDeckRoute: AuthenticatedVocabDeckRouteWithChildren,
  AuthenticatedVocabDecksRoute: AuthenticatedVocabDecksRoute,
  AuthenticatedVocabTestsRoute: AuthenticatedVocabTestsRouteWithChildren,
  AuthenticatedVocabIndexRoute: AuthenticatedVocabIndexRoute,
}

const AuthenticatedVocabRouteWithChildren =
  AuthenticatedVocabRoute._addFileChildren(AuthenticatedVocabRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAnalysisRoute: typeof AuthenticatedAnalysisRouteWithChildren
  AuthenticatedBeyondAiRoute: typeof AuthenticatedBeyondAiRoute
  AuthenticatedClassesRoute: typeof AuthenticatedClassesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFirstLoginRoute: typeof AuthenticatedFirstLoginRoute
  AuthenticatedLessonsRoute: typeof AuthenticatedLessonsRouteWithChildren
  AuthenticatedNewsRoute: typeof AuthenticatedNewsRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPracticeRoute: typeof AuthenticatedPracticeRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedVocabRoute: typeof AuthenticatedVocabRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAnalysisRoute: AuthenticatedAnalysisRouteWithChildren,
  AuthenticatedBeyondAiRoute: AuthenticatedBeyondAiRoute,
  AuthenticatedClassesRoute: AuthenticatedClassesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFirstLoginRoute: AuthenticatedFirstLoginRoute,
  AuthenticatedLessonsRoute: AuthenticatedLessonsRouteWithChildren,
  AuthenticatedNewsRoute: AuthenticatedNewsRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPracticeRoute: AuthenticatedPracticeRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedVocabRoute: AuthenticatedVocabRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  BannedRoute: BannedRoute,
  PrivacyRoute: PrivacyRoute,
  ProgramsRoute: ProgramsRoute,
  ResourcesRoute: ResourcesRoute,
  ResultsRoute: ResultsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
